-- =========================================================================
-- Finance Dashboard — seed.sql
-- Optional demo rows for local development. Run AFTER schema.sql.
-- password_hash below is a placeholder; replace with a real bcrypt hash
-- generated by hash_password() in auth.php once Phase 2 is in place.
-- =========================================================================

INSERT INTO users (first_name, last_name, email, password_hash, role)
VALUES
    ('Admin',   'User',    'admin@example.com',    '$2y$12$REPLACE_WITH_REAL_HASH_ADMIN', 'admin'),
    ('Manager', 'User',    'manager@example.com',  '$2y$12$REPLACE_WITH_REAL_HASH_MANAG', 'manager'),
    ('Employee','User',    'employee@example.com', '$2y$12$REPLACE_WITH_REAL_HASH_EMPLO', 'employee');

INSERT INTO categories (user_id, name, kind) VALUES
    (1, 'Salary',    'income'),
    (1, 'Rent',      'expense'),
    (1, 'Software',  'expense'),
    (1, 'Meals',     'expense'),
    (1, 'Travel',    'expense');

INSERT INTO accounts (user_id, name, type, currency, opening_balance) VALUES
    (1, 'Primary checking', 'bank', 'USD', 10000.00),
    (1, 'Corporate card',   'card', 'USD',     0.00);
